[manifest]
version = "1.0.0"
priority = 0

[[patches]] #For debuffed played cards
[patches.pattern]
target = '=[SMODS _ "src/utils.lua"]'
pattern = "--if card is debuffed"
position = "after"
match_indent = true
payload = '''
if scoring_hand and card.debuff then
    if in_scoring and next(SMODS.find_card("j_bgn_taboo")) then
        for k, v in pairs(SMODS.find_card("j_bgn_taboo")) do
            if card.debuff then
                SMODS.calculate_effect({xmult = v.ability.extra.xmult}, card)
            end
        end
    end
end
'''

[[patches]] #For debuffed joker cards
[patches.pattern]
target = "functions/common_events.lua"
pattern = "if not card:can_calculate(context.ignore_debuff, context.remove_playing_cards*"
position = "before"
match_indent = true
payload = '''
if context.joker_main and next(SMODS.find_card("j_bgn_taboo")) and not context.blueprint then
    for k, v in pairs(SMODS.find_card("j_bgn_taboo")) do
        if card.debuff then
            SMODS.calculate_effect({xmult = v.ability.extra.xmult}, card)
        end
    end
end
'''

[[patches]] #add hole punched card discard area, adapted from AIJ's line in the sand
[patches.pattern]
target = "game.lua"
pattern = "self.discard = CardArea("
position = "before"
match_indent = true
payload = '''
self.bgn_holepunched_discard = CardArea(
        0, 0,
        CAI.discard_W,CAI.discard_H,
        {card_limit = 1e308, type = 'discard'})
'''

[[patches]] 
[patches.pattern]
target = "functions/state_events.lua"
pattern = "draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])"
position = "at"
payload = '''
if SMODS.has_enhancement(G.hand.highlighted[i], "m_bgn_holepunched") then
    G.GAME.bgn_holepunchedtotal = (G.GAME.bgn_holepunchedtotal or 0) + 1
    draw_card(G.hand, G.bgn_holepunched_discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])
else
    draw_card(G.hand, G.discard, i*100/highlighted_count, 'down', false, G.hand.highlighted[i])
end
'''
match_indent = true

#[[patches]] 
#[patches.pattern]
#target = "functions/state_events.lua"
#pattern = "draw_card(G.play,G.discard, it*100/play_count,'down', false, v)"
#position = "at"
#payload = '''
#if SMODS.has_enhancement(v, "m_bgn_holepunched") then
    #draw_card(G.play, G.bgn_holepunched_discard, it*100/play_count,'down', false, v)
#else
    #draw_card(G.play,G.discard, it*100/play_count,'down', false, v)
#end
#'''
#match_indent = true

[[patches]] # only runs when boss is defeated
[patches.pattern]
target = "functions/state_events.lua"
pattern = "local discard_count = #G.discard.cards"
position = "before"
payload = '''
if #G.bgn_holepunched_discard.cards > 0 and G.GAME.blind.boss then
    local holepunched_discard_count = #G.bgn_holepunched_discard.cards
    for i=1, holepunched_discard_count do --draw cards from deck
        draw_card(G.bgn_holepunched_discard, G.deck, i*100/holepunched_discard_count,'up', nil ,nil, 0.005, i%2==0, nil, math.max((21-i)/20,0.7))
    end
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "if G.GAME.dollars >= 5 and not G.GAME.modifiers.no_interest then"
position = "before"
payload = '''
if G.GAME.bgn_holepunchedtotal then
    if G.GAME.bgn_holepunchedtotal > 0 then
        add_round_eval_row({dollars = (G.GAME.bgn_holepunchedtotal * 2), text = ' Hole Punched Cards ($2 each)', text_colour = G.C.WHITE, disp = G.GAME.bgn_holepunchedtotal, number = 1, number_colour = G.C.RED, bonus = true, name = 'other'..i , pitch = pitch })
        pitch = pitch + 0.06
        dollars = dollars + (G.GAME.bgn_holepunchedtotal * 2)
    end
end
if G.GAME.blind:get_type() == 'Boss' then
    G.GAME.bgn_holepunchedtotal = 0
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "elseif string.find(config.name, 'joker') then"
position = "before"
payload = '''
elseif string.find(config.name, 'other') then
    local loc_opts = config.loc_opts or {}
    table.insert(left_text, {n=G.UIT.T, config={text = config.disp, scale = 0.8*scale, colour = G.C.WHITE, shadow = true, juice = true}})
    table.insert(left_text, {n=G.UIT.O, config={object = DynaText({string = {""..config.text}, colours = {loc_opts.text_colour or G.C.WHITE}, shadow = true, pop_in = 0, scale = 0.4*scale, silent = true})}})
'''
match_indent = true

#ease_discard(-1)

[[patches]]
[patches.pattern]
target = "functions/state_events.lua"
pattern = "ease_discard(-1)"
position = "at"
payload = '''
if G.GAME.bgn_onlyhands == true then
    ease_hands_played(-1)
else
    ease_discard(-1)
end
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "if G.GAME.current_round.discards_left <= 0 or #G.hand.highlighted <= 0 or #G.hand.highlighted > math.max(G.GAME.starting_params.discard_limit, 0) then"
position = "at"
payload = '''
if ((G.GAME.current_round.discards_left <= 0) and not G.GAME.bgn_onlyhands) or ((G.GAME.current_round.hands_left <= 1) and G.GAME.bgn_onlyhands) or #G.hand.highlighted <= 0 or #G.hand.highlighted > math.max(G.GAME.starting_params.discard_limit, 0) then
'''
match_indent = true

[[patches]]
[patches.pattern]
target = "functions/common_events.lua"
pattern = "G.GAME.current_round.hands_left = G.GAME.current_round.hands_left + mod"
position = "after"
payload = '''
if G.GAME.bgn_onlyhands then
    G.GAME.current_round.discards_left = G.GAME.current_round.hands_left + mod
end
'''
match_indent = true